/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import components.ButtonRenderer;
import dao.ClassesDAO;
import dao.SubjectsDAO;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import model.Classes;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import model.Subject;

/**
 *
 * @author vulebaolong
 */
public class StudentPanel extends javax.swing.JPanel {

    private ClassesDAO classesDAO;
    private SubjectsDAO subjectsDAO;

    /**
     * Creates new form StudentPanel
     */
    public StudentPanel() {
        initComponents();
        classesDAO = new ClassesDAO();
        subjectsDAO = new SubjectsDAO();

        loadClassesData();
        loadSubjectsData();
    }

    private void loadClassesData() {
        List<Classes> classes = classesDAO.getAllClasses();

        // Lấy model của JTable
        DefaultTableModel modelClasses = (DefaultTableModel) tbListClasses.getModel();
        modelClasses.setRowCount(0); // Xóa dữ liệu cũ

        // Thêm từng sinh viên vào bảng
        for (Classes s : classes) {
            modelClasses.addRow(new Object[]{
                s.getId(),
                s.getClassName(),
                s.getDepartment(),
                "Xóa"
            });
        }

//        tbListClasses.getColumnModel().getColumn(3).setCellRenderer(new ButtonRenderer());
//        tbListClasses.getColumnModel().getColumn(3).setCellEditor(new ButtonEditor(new JCheckBox(), this));

    }

    private void loadSubjectsData() {
        List<Subject> subject = subjectsDAO.getAllSubjects();

        DefaultTableModel modelSubjects = (DefaultTableModel) tbListSubjects.getModel();
        modelSubjects.setRowCount(0);

        for (Subject s : subject) {
            modelSubjects.addRow(new Object[]{
                s.getId(),
                s.getSubjectName(),
                s.getCredit()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListClasses = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbListSubjects = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setText("Danh Sách Lớp Học");

        tbListClasses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Tên Lớp", "Ngành", "Action"
            }
        ));
        jScrollPane1.setViewportView(tbListClasses);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setText("Danh Sách Môn Học");

        tbListSubjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Tên Môn Học", "Tín Chỉ"
            }
        ));
        jScrollPane2.setViewportView(tbListSubjects);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbListClasses;
    private javax.swing.JTable tbListSubjects;
    // End of variables declaration//GEN-END:variables
}
